# Generated by Django 4.0.4 on 2022-11-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, max_length=128, verbose_name='帖子ID')),
                ('title', models.CharField(blank=True, max_length=1024, verbose_name='标题')),
                ('img_url', models.CharField(blank=True, max_length=2048, verbose_name='图片')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='帖子地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '贴吧贴子',
                'verbose_name_plural': '贴吧贴子',
                'db_table': 'baidu_post',
            },
        ),
        migrations.CreateModel(
            name='BaiduUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='贴吧用户名')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '贴吧用户',
                'verbose_name_plural': '贴吧用户',
                'db_table': 'baidu_user',
            },
        ),
        migrations.CreateModel(
            name='BaiduComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=2048, verbose_name='评论')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('BaiduPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Tieba.baidupost', verbose_name='对应帖子')),
                ('BaiduUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='Tieba.baiduuser', verbose_name='百度用户')),
            ],
            options={
                'verbose_name': '贴吧一级评论',
                'verbose_name_plural': '贴吧一级评论',
                'db_table': 'baidu_comment',
            },
        ),
    ]
