# Generated by Django 4.0.4 on 2022-11-23 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_file', models.FileField(upload_to='upload/', verbose_name='上传文件')),
                ('handle_text', models.TextField(blank=True, null=True, verbose_name='处理信息')),
            ],
            options={
                'verbose_name': '批量导入用户信息',
                'verbose_name_plural': '批量导入用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('identity_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证后八位')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机')),
                ('classes', models.CharField(blank=True, max_length=50, verbose_name='所在班级')),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=50, null=True, verbose_name='性别')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='用户', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
