# Generated by Django 4.0.4 on 2022-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, null=True, verbose_name='班级')),
                ('class_teacher', models.CharField(max_length=50, null=True, verbose_name='分管辅导员')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='TeacherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('teacher_server_chan_url', models.CharField(max_length=200, null=True, verbose_name='server chan URL')),
            ],
            options={
                'verbose_name': '辅导员',
                'verbose_name_plural': '辅导员',
            },
        ),
    ]
