# Generated by Django 4.0.4 on 2022-11-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('article', models.CharField(max_length=500, verbose_name='文章')),
                ('likes_num', models.IntegerField(verbose_name='点赞数')),
                ('comment_num', models.IntegerField(verbose_name='评论数')),
                ('transmit_num', models.IntegerField(verbose_name='转发数')),
                ('c_time', models.CharField(max_length=50, verbose_name='最后回复时间')),
                ('pic_links', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片链接')),
                ('art_links', models.CharField(blank=True, max_length=200, null=True, verbose_name='文章链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '微博帖子',
                'verbose_name_plural': '微博帖子',
            },
        ),
        migrations.CreateModel(
            name='WeiboFirstComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('context', models.CharField(max_length=500, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstcomment', to='Weibo.weiboarticle', verbose_name='文章')),
            ],
            options={
                'verbose_name': '微博一级评论',
                'verbose_name_plural': '微博一级评论',
            },
        ),
        migrations.CreateModel(
            name='WeiboSecondComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('context', models.CharField(max_length=500, verbose_name='评论回复内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondcomment', to='Weibo.weiboarticle', verbose_name='文章')),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondcomment', to='Weibo.weibofirstcomment', verbose_name='一级评论')),
            ],
            options={
                'verbose_name': '微博二级评论',
                'verbose_name_plural': '微博二级评论',
            },
        ),
    ]
